export const aArtworks = [
  {
    title: "In Poppyland (Poppy field)",
    year: "1901",
    originalSize: "56 x 81.6 cm",
    artist: "John Otis Adams",
    artistLife: "1851-1927",
    sku: "AM-JOA-001",
    basePrice: 3200,
    currency: "AED",
    image: "/image/a/in poppyland (poppy field).jpg",
    options: [{ id: 'opt1', width: 56, height: 81.6, price: 3200, label: 'Original Size' }],
  },

  {
    title: "Gleaners At Rest",
    year: "1886",
    originalSize: "73 x 99.1 cm",
    artist: "John Otis Adams",
    artistLife: "1851-1927",
    sku: "AM-JOA-002",
    basePrice: 4300,
    currency: "AED",
    image: "/image/a/gleaners at rest.jpg",
    options: [{ id: 'opt1', width: 73, height: 99.1, price: 4300, label: 'Original Size' }],
  },

  {
    title: "Iridesence Of A Shallow Stream",
    year: "1902",
    originalSize: "71 x 106.8 cm",
    artist: "John Otis Adams",
    artistLife: "1851-1927",
    sku: "AM-JOA-003",
    basePrice: 4350,
    currency: "AED",
    image: "/image/a/iridesence of a shallow stream.jpg",
    options: [{ id: 'opt1', width: 71, height: 106.8, price: 4350, label: 'Original Size' }],
  },

  {
    title: "Wheatwain A Field",
    year: "1894",
    originalSize: "62.2 x 88.9 cm",
    artist: "John Otis Adams",
    artistLife: "1851-1927",
    sku: "AM-JOA-004",
    basePrice: 4100,
    currency: "AED",
    image: "/image/a/wheatwain a field.jpg",
    options: [{ id: 'opt1', width: 62.2, height: 88.9, price: 4100, label: 'Original Size' }],
  },

  {
    title: "Glass Vase With Branches Bearing Fruit",
    year: "1664",
    originalSize: "67.3 x 52.1 cm",
    artist: "Wilem Van Aelst",
    artistLife: "1627-1683",
    sku: "AM-WVA-001",
    basePrice: 9080,
    currency: "AED",
    image: "/image/a/glass vase with branches bearing fruit.jpg",
    options: [{ id: 'opt1', width: 67.3, height: 52.1, price: 9080, label: 'Original Size' }],
  },

  {
    title: "Still Life With A Basket Of Fruit On A Marble Edge",
    year: "1650",
    originalSize: "38 x 50 cm",
    artist: "Wilem Van Aelst",
    artistLife: "1627-1683",
    sku: "AM-WVA-002",
    basePrice: 7029,
    currency: "AED",
    image: "/image/a/still life with a basket of fruit on a marble edge.jpg",
    options: [{ id: 'opt1', width: 38, height: 50, price: 7029, label: 'Original Size' }],
  },

  {
    title: "Still Life Fruit And Crystal Vase",
    year: "1652",
    originalSize: "73 x 58 cm",
    artist: "Wilem Van Aelst",
    artistLife: "1627-1683",
    sku: "AM-WVA-003",
    basePrice: 9227,
    currency: "AED",
    image: "/image/a/still life fruit and crystal vase.jpg",
    options: [{ id: 'opt1', width: 73, height: 58, price: 9227, label: 'Original Size' }],
  },

  {
    title: "Still Life Grapes, A Roemer, A Silver Ewer And A Plate",
    year: "1659",
    originalSize: "70.1 x 45.4 cm",
    artist: "Wilem Van Aelst",
    artistLife: "1627-1683",
    sku: "AM-WVA-004",
    basePrice: 9930,
    currency: "AED",
    image: "/image/a/still life grapes, a roemer, a silver ewer and a plate.jpg",
    options: [{ id: 'opt1', width: 70.1, height: 45.4, price: 9930, label: 'Original Size' }],
  },

  {
    title: "The Breakfast",
    year: "1679",
    originalSize: "57.5 x 46 cm",
    artist: "Wilem Van Aelst",
    artistLife: "1627-1683",
    sku: "AM-WVA-005",
    basePrice: 7325,
    currency: "AED",
    image: "/image/a/the breakfast.jpg",
    options: [{ id: 'opt1', width: 57.5, height: 46, price: 7325, label: 'Original Size' }],
  },

  {
    title: "Still Life of a Silver Tazza with a Wine Glass, Crab, Herring, Bread and Onion on Pewter Dishes with Grapes Arranged on a Ledge",
    year: "1682",
    originalSize: "58 x 46.5 cm",
    artist: "Wilem Van Aelst",
    artistLife: "1627-1683",
    sku: "AM-WVA-006",
    basePrice: 6980,
    currency: "AED",
    image: "/image/a/Still Life of a Silver Tazza with a Wine Glass, Crab, Herring, Bread and Onion on Pewter Dishes with Grapes Arranged on a Ledge.jpg",
    options: [{ id: 'opt1', width: 58, height: 46.5, price: 6980, label: 'Original Size' }],
  },

  {
    title: "Still Life Herring, Cherries And Glassware",
    year: "1680",
    originalSize: "50.2 x 42.5 cm",
    artist: "Wilem Van Aelst",
    artistLife: "1627-1683",
    sku: "AM-WVA-007",
    basePrice: 6560,
    currency: "AED",
    image: "/image/a/still life herring, cherries and glassware.jpg",
    options: [{ id: 'opt1', width: 50.2, height: 42.5, price: 6560, label: 'Original Size' }],
  },

  {
    title: "Still Life A Velvet Bag On A Marble Edge",
    year: "1665",
    originalSize: "67.3 x 54 cm",
    artist: "Wilem Van Aelst",
    artistLife: "1627-1683",
    sku: "AM-WVA-008",
    basePrice: 7900,
    currency: "AED",
    image: "/image/a/still life a velvet bag on a marble ledge.jpg",
    options: [{ id: 'opt1', width: 67.3, height: 54, price: 7900, label: 'Original Size' }],
  },

  {
    title: "Still Life With Dead Birds And Game Bag",
    year: "1674",
    originalSize: "45.1 x 36.8 cm",
    artist: "Wilem Van Aelst",
    artistLife: "1627-1683",
    sku: "AM-WVA-009",
    basePrice: 7029,
    currency: "AED",
    image: "/image/a/still life with dead birds and game bag.jpg",
    options: [{ id: 'opt1', width: 45.1, height: 36.8, price: 7029, label: 'Original Size' }],
  },

  {
    title: "The Market Scene",
    year: "1569",
    originalSize: "83.5 x 169.5 cm",
    artist: "Pieter Aertsen",
    artistLife: "1508-1575",
    sku: "AM-PA-001",
    basePrice: 9200,
    currency: "AED",
    image: "/image/a/the market scene.jpg",
    options: [{ id: 'opt1', width: 83.5, height: 169.5, price: 9200, label: 'Original Size' }],
  },

  {
    title: "The Egg Dance",
    year: "1552",
    originalSize: "84 x 172 cm",
    artist: "Pieter Aertsen",
    artistLife: "1508-1575",
    sku: "AM-PA-002",
    basePrice: 9250,
    currency: "AED",
    image: "/image/a/the egg dance.jpg",
    options: [{ id: 'opt1', width: 84, height: 172, price: 9250, label: 'Original Size' }],
  },

  {
    title: "Butchers Stall With The Flight In To Egypt",
    year: "1551",
    originalSize: "123 x 175 cm",
    artist: "Pieter Aertsen",
    artistLife: "1508-1575",
    sku: "AM-PA-003",
    basePrice: 10300,
    currency: "AED",
    image: "/image/a/butches stall with the flight in to egypt.jpg",
    options: [{ id: 'opt1', width: 123, height: 175, price: 10300, label: 'Original Size' }],
  },

  {
    title: "The Cook",
    year: "1569",
    originalSize: "66 x 32 cm",
    artist: "Pieter Aertsen",
    artistLife: "1508-1575",
    sku: "AM-PA-004",
    basePrice: 3521,
    currency: "AED",
    image: "/image/a/the cook.jpg",
    options: [{ id: 'opt1', width: 66, height: 32, price: 3521, label: 'Original Size' }],
  },

  {
    title: "Vendor Of Fowl",
    year: "1560",
    originalSize: "137 x 95 cm",
    artist: "Pieter Aertsen",
    artistLife: "1508-1575",
    sku: "AM-PA-005",
    basePrice: 8700,
    currency: "AED",
    image: "/image/a/vendor of fowl.jpg",
    options: [{ id: 'opt1', width: 137, height: 95, price: 8700, label: 'Original Size' }],
  },

  {
    title: "Market Woman At A Vegetable Stand",
    year: "1567",
    originalSize: "111.2 x 111.6 cm",
    artist: "Pieter Aertsen",
    artistLife: "1508-1575",
    sku: "AM-PA-006",
    basePrice: 7890,
    currency: "AED",
    image: "/image/a/marketwoman at a vegetable stand.jpg",
    options: [{ id: 'opt1', width: 111.2, height: 111.6, price: 7890, label: 'Original Size' }],
  },

  {
    title: "The Nubian Giraffe",
    year: "1827",
    originalSize: "127.3 x 101.7 cm",
    artist: "Jaques-Laurent Agasse",
    artistLife: "1767-1849",
    sku: "AM-JLA-001",
    basePrice: 10635,
    currency: "AED",
    image: "/image/a/the nubian giraffe.jpg",
    options: [{ id: 'opt1', width: 127.3, height: 101.7, price: 10635, label: 'Original Size' }],
  },

  {
    title: "A Pointer In Landscape",
    year: "1825",
    originalSize: "48 x 60 cm",
    artist: "Jaques-Laurent Agasse",
    artistLife: "1767-1849",
    sku: "AM-JLA-002",
    basePrice: 4088,
    currency: "AED",
    image: "/image/a/a pointer in landscape.jpg",
    options: [{ id: 'opt1', width: 48, height: 60, price: 4088, label: 'Original Size' }],
  },

  {
    title: "Deperture To The Hunt",
    year: "1803",
    originalSize: "68 x 81 cm",
    artist: "Jaques-Laurent Agasse",
    artistLife: "1767-1849",
    sku: "AM-JLA-003",
    basePrice: 5100,
    currency: "AED",
    image: "/image/a/deperture to the hunt.jpg",
    options: [{ id: 'opt1', width: 68, height: 81, price: 5100, label: 'Original Size' }],
  },

  {
    title: "The Playground",
    year: "1830",
    originalSize: "70 x 90 cm",
    artist: "Jaques-Laurent Agasse",
    artistLife: "1767-1849",
    sku: "AM-JLA-004",
    basePrice: 5100,
    currency: "AED",
    image: "/image/a/the playground.jpg",
    options: [{ id: 'opt1', width: 70, height: 90, price: 5100, label: 'Original Size' }],
  },

  {
    title: "The Rainbow",
    year: "1873",
    originalSize: "102 x 132 cm",
    artist: "Ivan Konstantinovich Aivazovsky",
    artistLife: "1817-1900",
    sku: "AM-IKA-001",
    basePrice: 4450,
    currency: "AED",
    image: "/image/a/the rainbow.jpg",
    options: [{ id: 'opt1', width: 102, height: 132, price: 4450, label: 'Original Size' }],
  },

  {
    title: "Boat On The Nile With Pyramids Of Gizeh",
    year: "1872",
    originalSize: "73 x 92 cm",
    artist: "Ivan Konstantinovich Aivazovsky",
    artistLife: "1817-1900",
    sku: "AM-IKA-002",
    basePrice: 5335,
    currency: "AED",
    image: "/image/a/boat on the nile with pyramids of gizeh.jpg",
    options: [{ id: 'opt1', width: 73, height: 92, price: 5335, label: 'Original Size' }],
  },

  {
    title: "Sunrise In Yalta",
    year: "1878",
    originalSize: "102 x 132 cm",
    artist: "Ivan Konstantinovich Aivazovsky",
    artistLife: "1817-1900",
    sku: "AM-IKA-003",
    basePrice: 6590,
    currency: "AED",
    image: "/image/a/sunrise in yalta.jpg",
    options: [{ id: 'opt1', width: 102, height: 132, price: 6590, label: 'Original Size' }],
  },

  {
    title: "The Ninth Wave",
    year: "1850",
    originalSize: "221 x 332 cm",
    artist: "Ivan Konstantinovich Aivazovsky",
    artistLife: "1817-1900",
    sku: "AM-IKA-004",
    basePrice: 59000,
    currency: "AED",
    image: "/image/a/the ninth wave.jpg",
    options: [{ id: 'opt1', width: 221, height: 332, price: 59000, label: 'Original Size' }],
  },

  {
    title: "Repose",
    year: "1895",
    originalSize: "132.7 x 161.6 cm",
    artist: "John White Alexander",
    artistLife: "1856-1915",
    sku: "AM-JWA-001",
    basePrice: 3142,
    currency: "AED",
    image: "/image/a/repose.jpg",
    options: [{ id: 'opt1', width: 132.7, height: 161.6, price: 3142, label: 'Original Size' }],
  },

  {
    title: "Repose (Lady Reading A Book)",
    year: "1895",
    originalSize: "31 x 39 cm",
    artist: "John White Alexander",
    artistLife: "1856-1915",
    sku: "AM-JWA-002",
    basePrice: 3486,
    currency: "AED",
    image: "/image/a/repose (lady reading book).jpg",
    options: [{ id: 'opt1', width: 31, height: 39, price: 3486, label: 'Original Size' }],
  },

  {
    title: "Study In Green And Black",
    year: "1906",
    originalSize: "127 x 101.9 cm",
    artist: "John White Alexander",
    artistLife: "1856-1915",
    sku: "AM-JWA-003",
    basePrice: 5200,
    currency: "AED",
    image: "/image/a/study in green and black.jpg",
    options: [{ id: 'opt1', width: 127, height: 101.9, price: 5200, label: 'Original Size' }],
  },

  {
    title: "Isabella Pot Of Basil",
    year: "1897",
    originalSize: "192.09 x 91.76 cm",
    artist: "John White Alexander",
    artistLife: "1856-1915",
    sku: "AM-JWA-004",
    basePrice: 10100,
    currency: "AED",
    image: "/image/a/isabella pot of basil.jpg",
    options: [{ id: 'opt1', width: 192.09, height: 91.76, price: 10100, label: 'Original Size' }],
  },

  {
    title: "The favourite Poet",
    year: "1889",
    originalSize: "36.9 x 49.6 cm",
    artist: "Sir Lawreance Alma-Tadema",
    artistLife: "1836-1912",
    sku: "AM-SLT-001",
    basePrice: 5840,
    currency: "AED",
    image: "/image/a/the favourite poet.jpg",
    options: [{ id: 'opt1', width: 36.9, height: 49.6, price: 5840, label: 'Original Size' }],
  },

  {
    title: "The Coign Of Vantage",
    year: "1895",
    originalSize: "64.2 x 45 cm",
    artist: "Sir Lawreance Alma-Tadema",
    artistLife: "1836-1912",
    sku: "AM-SLT-002",
    basePrice: 5662,
    currency: "AED",
    image: "/image/a/the coign of vantage.jpg",
    options: [{ id: 'opt1', width: 64.2, height: 45, price: 5662, label: 'Original Size' }],
  },

  {
    title: "The Years At Spring. All's Right With The World",
    year: "1902",
    originalSize: "70 x 50 cm",
    artist: "Sir Lawreance Alma-Tadema",
    artistLife: "1836-1912",
    sku: "AM-SLT-003",
    basePrice: 5600,
    currency: "AED",
    image: "/image/a/the years at spring. all's right with the world.jpg",
    options: [{ id: 'opt1', width: 70, height: 50, price: 5600, label: 'Original Size' }],
  },

  {
    title: "Under The Roof Of The Blue Ionion Weather",
    year: "1901",
    originalSize: "55 x 120.5 cm",
    artist: "Sir Lawreance Alma-Tadema",
    artistLife: "1836-1912",
    sku: "AM-SLT-004",
    basePrice: 7588,
    currency: "AED",
    image: "/image/a/under the roof of the blue ionion weather.jpg",
    options: [{ id: 'opt1', width: 55, height: 120.5, price: 7588, label: 'Original Size' }],
  },

];

export default aArtworks;
