export const cArtworks = [
  {
    title: "Entrance To The Grand Canal Looking West",
    year: "1730",
    originalSize: "49.5 x 72.4 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-001",
    basePrice: 5500,
    currency: "AED",
    image: "/image/c/entrance to the grand canal looking west.jpg",
    options: [{ id: 'opt1', width: 49.5, height: 72.4, price: 5500, label: 'Original Size' }],
  },

  {
    title: "Venice Facade",
    year: "1735",
    originalSize: "143 x 199.5 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-002",
    basePrice: 18500,
    currency: "AED",
    image: "/image/c/venice facade.jpg",
    options: [{ id: 'opt1', width: 143, height: 199.5, price: 18500, label: 'Original Size' }],
  },

  {
    title: "Piazza San Marco With The Cathedral",
    year: "1730",
    originalSize: "68.5 x 93.5 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-003",
    basePrice: 8500,
    currency: "AED",
    image: "/image/c/piazza san marco with the cathedral.jpg",
    options: [{ id: 'opt1', width: 68.5, height: 93.5, price: 8500, label: 'Original Size' }],
  },

  {
    title: "Grand Canal From Palazzo Balbi",
    year: "1724",
    originalSize: "144.8 x 207.6 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-004",
    basePrice: 22000,
    currency: "AED",
    image: "/image/c/grand canal from palazzo balbi.jpg",
    options: [{ id: 'opt1', width: 144.8, height: 207.6, price: 22000, label: 'Original Size' }],
  },

  {
    title: "The Entrance To Grand Canal Venice",
    year: "1730",
    originalSize: "49.2 x 72.7 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-005",
    basePrice: 5600,
    currency: "AED",
    image: "/image/c/the entrance to grand canal venice.jpg",
    options: [{ id: 'opt1', width: 49.2, height: 72.7, price: 5600, label: 'Original Size' }],
  },

  {
    title: "Venice The Ineerior Of St Marco By Day",
    year: "1755",
    originalSize: "37 x 38.5 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-006",
    basePrice: 3800,
    currency: "AED",
    image: "/image/c/venice the ineerior of st marco by day.jpg",
    options: [{ id: 'opt1', width: 37, height: 38.5, price: 3800, label: 'Original Size' }],
  },

  {
    title: "Capriccio With Colonnade In The Interior Of The Palace",
    year: "1765",
    originalSize: "131 x 93 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-007",
    basePrice: 11000,
    currency: "AED",
    image: "/image/c/capriccio with colonnade in the interior of the palace.jpg",
    options: [{ id: 'opt1', width: 131, height: 93, price: 11000, label: 'Original Size' }],
  },

  {
    title: "View Of Grand Canal From San Vio Venice",
    year: "1723",
    originalSize: "140.5 x 204.5 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-008",
    basePrice: 21000,
    currency: "AED",
    image: "/image/c/view of grand canal from san vio venice.jpg",
    options: [{ id: 'opt1', width: 140.5, height: 204.5, price: 21000, label: 'Original Size' }],
  },

  {
    title: "Piazetta And The Doge's Palace",
    year: "1730",
    originalSize: "50 x 70 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-009",
    basePrice: 5400,
    currency: "AED",
    image: "/image/c/piazetta and the doge's palace.jpg",
    options: [{ id: 'opt1', width: 50, height: 70, price: 5400, label: 'Original Size' }],
  },

  {
    title: "View Of Rialto Bridge At Venice South",
    year: "1730",
    originalSize: "144.8 x 207.6 cm",
    artist: "Canaletto",
    artistLife: "1697-1768",
    sku: "AM-CAN-010",
    basePrice: 22000,
    currency: "AED",
    image: "/image/c/view of rialto bridge at venice south.jpg",
    options: [{ id: 'opt1', width: 144.8, height: 207.6, price: 22000, label: 'Original Size' }],
  },

  {
    title: "Bacchus",
    year: "1596",
    originalSize: "95 x 85 cm",
    artist: "Caravaggio",
    artistLife: "1571-1610",
    sku: "AM-CAR-001",
    basePrice: 9500,
    currency: "AED",
    image: "/image/c/bacchus.jpg",
    options: [{ id: 'opt1', width: 95, height: 85, price: 9500, label: 'Original Size' }],
  },

  {
    title: "The Calling Of Saint Matthew",
    year: "1600",
    originalSize: "322 x 340 cm",
    artist: "Caravaggio",
    artistLife: "1571-1610",
    sku: "AM-CAR-002",
    basePrice: 65000,
    currency: "AED",
    image: "/image/c/the calling of saint matthew.jpg",
    options: [{ id: 'opt1', width: 322, height: 340, price: 65000, label: 'Original Size' }],
  },

  {
    title: "Judith Beheading Holofernes",
    year: "1599",
    originalSize: "145 x 195 cm",
    artist: "Caravaggio",
    artistLife: "1571-1610",
    sku: "AM-CAR-003",
    basePrice: 22000,
    currency: "AED",
    image: "/image/c/judith beheading holofernes.jpg",
    options: [{ id: 'opt1', width: 145, height: 195, price: 22000, label: 'Original Size' }],
  },

  {
    title: "The Supper At Emmaus",
    year: "1601",
    originalSize: "141 x 196.2 cm",
    artist: "Caravaggio",
    artistLife: "1571-1610",
    sku: "AM-CAR-004",
    basePrice: 21000,
    currency: "AED",
    image: "/image/c/the supper at emmaus.jpg",
    options: [{ id: 'opt1', width: 141, height: 196.2, price: 21000, label: 'Original Size' }],
  },

  {
    title: "David With The Head Of Goliath",
    year: "1610",
    originalSize: "125 x 101 cm",
    artist: "Caravaggio",
    artistLife: "1571-1610",
    sku: "AM-CAR-005",
    basePrice: 11000,
    currency: "AED",
    image: "/image/c/david with the head of goliath.jpg",
    options: [{ id: 'opt1', width: 125, height: 101, price: 11000, label: 'Original Size' }],
  },

  {
    title: "The Conversion Of Saint Paul",
    year: "1601",
    originalSize: "230 x 175 cm",
    artist: "Caravaggio",
    artistLife: "1571-1610",
    sku: "AM-CAR-006",
    basePrice: 28000,
    currency: "AED",
    image: "/image/c/the conversion of saint paul.jpg",
    options: [{ id: 'opt1', width: 230, height: 175, price: 28000, label: 'Original Size' }],
  },

  {
    title: "Paris Street Rainy Weather",
    year: "1877",
    originalSize: "212.2 x 276.2 cm",
    artist: "Gustave Caillebotte",
    artistLife: "1848-1894",
    sku: "AM-GC-001",
    basePrice: 42000,
    currency: "AED",
    image: "/image/c/paris street rainy weather.jpg",
    options: [{ id: 'opt1', width: 212.2, height: 276.2, price: 42000, label: 'Original Size' }],
  },

  {
    title: "Young Man At His Window",
    year: "1876",
    originalSize: "116.2 x 80.9 cm",
    artist: "Gustave Caillebotte",
    artistLife: "1848-1894",
    sku: "AM-GC-002",
    basePrice: 10500,
    currency: "AED",
    image: "/image/c/young man at his window.jpg",
    options: [{ id: 'opt1', width: 116.2, height: 80.9, price: 10500, label: 'Original Size' }],
  },

  {
    title: "The Floor Scrapers",
    year: "1875",
    originalSize: "102 x 146.5 cm",
    artist: "Gustave Caillebotte",
    artistLife: "1848-1894",
    sku: "AM-GC-003",
    basePrice: 13500,
    currency: "AED",
    image: "/image/c/the floor scrapers.jpg",
    options: [{ id: 'opt1', width: 102, height: 146.5, price: 13500, label: 'Original Size' }],
  },

  {
    title: "The Yerres Rain (Riverbank In The Rain)",
    year: "1875",
    originalSize: "81 x 59 cm",
    artist: "Gustave Caillebotte",
    artistLife: "1848-1894",
    sku: "AM-GC-004",
    basePrice: 6800,
    currency: "AED",
    image: "/image/c/the yerres rain (riverbank in the rain).jpg",
    options: [{ id: 'opt1', width: 81, height: 59, price: 6800, label: 'Original Size' }],
  },

  {
    title: "View Of The Roof Snow Effect",
    year: "1878",
    originalSize: "65 x 82 cm",
    artist: "Gustave Caillebotte",
    artistLife: "1848-1894",
    sku: "AM-GC-005",
    basePrice: 7200,
    currency: "AED",
    image: "/image/c/view of the roof snow effect.jpg",
    options: [{ id: 'opt1', width: 65, height: 82, price: 7200, label: 'Original Size' }],
  },

  {
    title: "Monte Sainte-Victoire",
    year: "1887",
    originalSize: "67 x 92 cm",
    artist: "Paul Cezanne",
    artistLife: "1839-1906",
    sku: "AM-PC-001",
    basePrice: 8500,
    currency: "AED",
    image: "/image/c/monte sainte-victoire.jpg",
    options: [{ id: 'opt1', width: 67, height: 92, price: 8500, label: 'Original Size' }],
  },

  {
    title: "The Card Players",
    year: "1895",
    originalSize: "47.5 x 57 cm",
    artist: "Paul Cezanne",
    artistLife: "1839-1906",
    sku: "AM-PC-002",
    basePrice: 4800,
    currency: "AED",
    image: "/image/c/the card players.jpg",
    options: [{ id: 'opt1', width: 47.5, height: 57, price: 4800, label: 'Original Size' }],
  },

  {
    title: "The Bathers",
    year: "1900",
    originalSize: "127.2 x 196.1 cm",
    artist: "Paul Cezanne",
    artistLife: "1839-1906",
    sku: "AM-PC-003",
    basePrice: 19000,
    currency: "AED",
    image: "/image/c/the bathers.jpg",
    options: [{ id: 'opt1', width: 127.2, height: 196.1, price: 19000, label: 'Original Size' }],
  },

  {
    title: "View Through The Tress L' Estaque",
    year: "1879",
    originalSize: "71 x 58.3 cm",
    artist: "Paul Cezanne",
    artistLife: "1839-1906",
    sku: "AM-PC-004",
    basePrice: 6200,
    currency: "AED",
    image: "/image/c/view through the tress l' estaque.jpg",
    options: [{ id: 'opt1', width: 71, height: 58.3, price: 6200, label: 'Original Size' }],
  },

  {
    title: "Still Life With Apples",
    year: "1895",
    originalSize: "68.8 x 92.7 cm",
    artist: "Paul Cezanne",
    artistLife: "1839-1906",
    sku: "AM-PC-005",
    basePrice: 8600,
    currency: "AED",
    image: "/image/c/still life with apples.jpg",
    options: [{ id: 'opt1', width: 68.8, height: 92.7, price: 8600, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Cardinal Richelieu",
    year: "1637",
    originalSize: "260 x 178 cm",
    artist: "Philippe de Champaigne",
    artistLife: "1602-1674",
    sku: "AM-PDC-001",
    basePrice: 35000,
    currency: "AED",
    image: "/image/c/portrait of cardinal richelieu.jpg",
    options: [{ id: 'opt1', width: 260, height: 178, price: 35000, label: 'Original Size' }],
  },

  {
    title: "Triple Portrait Of Cardinal Richelieu",
    year: "1642",
    originalSize: "58.7 x 72.4 cm",
    artist: "Philippe de Champaigne",
    artistLife: "1602-1674",
    sku: "AM-PDC-002",
    basePrice: 6500,
    currency: "AED",
    image: "/image/c/triple portrait of cardinal richelieu.jpg",
    options: [{ id: 'opt1', width: 58.7, height: 72.4, price: 6500, label: 'Original Size' }],
  },

  {
    title: "Still Life Bread And Eggs",
    year: "1760",
    originalSize: "47 x 56 cm",
    artist: "Jean-Baptiste-Simeon Chardin",
    artistLife: "1699-1779",
    sku: "AM-JBSC-001",
    basePrice: 4800,
    currency: "AED",
    image: "/image/c/still life bread and eggs.jpg",
    options: [{ id: 'opt1', width: 47, height: 56, price: 4800, label: 'Original Size' }],
  },

  {
    title: "Glass Of Water And Coffee Pot",
    year: "1760",
    originalSize: "32.5 x 41 cm",
    artist: "Jean-Baptiste-Simeon Chardin",
    artistLife: "1699-1779",
    sku: "AM-JBSC-002",
    basePrice: 3500,
    currency: "AED",
    image: "/image/c/glass of water and coffee pot.jpg",
    options: [{ id: 'opt1', width: 32.5, height: 41, price: 3500, label: 'Original Size' }],
  },

  {
    title: "Still Life Asparagus And Red Currants",
    year: "1750",
    originalSize: "49 x 57 cm",
    artist: "Jean-Baptiste-Simeon Chardin",
    artistLife: "1699-1779",
    sku: "AM-JBSC-003",
    basePrice: 5000,
    currency: "AED",
    image: "/image/c/still life asparagus and red currants.jpg",
    options: [{ id: 'opt1', width: 49, height: 57, price: 5000, label: 'Original Size' }],
  },

  {
    title: "Basket Of Wild Strawberries",
    year: "1761",
    originalSize: "38 x 46 cm",
    artist: "Jean-Baptiste-Simeon Chardin",
    artistLife: "1699-1779",
    sku: "AM-JBSC-004",
    basePrice: 4200,
    currency: "AED",
    image: "/image/c/basket of wild strawberries.jpg",
    options: [{ id: 'opt1', width: 38, height: 46, price: 4200, label: 'Original Size' }],
  },

  {
    title: "A Breakfast Still Life With Strawberries And Cherries",
    year: "1750",
    originalSize: "38 x 46 cm",
    artist: "Jean-Baptiste-Simeon Chardin",
    artistLife: "1699-1779",
    sku: "AM-JBSC-005",
    basePrice: 4200,
    currency: "AED",
    image: "/image/c/a breakfast still life with strawberries and cherries.jpg",
    options: [{ id: 'opt1', width: 38, height: 46, price: 4200, label: 'Original Size' }],
  },

  {
    title: "Vanitas Still Life (Violin)",
    year: "1628",
    originalSize: "36 x 59 cm",
    artist: "Pieter Claesz",
    artistLife: "1597-1660",
    sku: "AM-PCL-001",
    basePrice: 4000,
    currency: "AED",
    image: "/image/c/vanitas still life (violin).jpg",
    options: [{ id: 'opt1', width: 36, height: 59, price: 4000, label: 'Original Size' }],
  },

  {
    title: "Still Life With Crab",
    year: "1644",
    originalSize: "61.5 x 46 cm",
    artist: "Pieter Claesz",
    artistLife: "1597-1660",
    sku: "AM-PCL-002",
    basePrice: 5200,
    currency: "AED",
    image: "/image/c/still life with crab.jpg",
    options: [{ id: 'opt1', width: 61.5, height: 46, price: 5200, label: 'Original Size' }],
  },

  {
    title: "Still Life With Oysters",
    year: "1640",
    originalSize: "38.5 x 56 cm",
    artist: "Pieter Claesz",
    artistLife: "1597-1660",
    sku: "AM-PCL-003",
    basePrice: 4100,
    currency: "AED",
    image: "/image/c/still life with oysters.jpg",
    options: [{ id: 'opt1', width: 38.5, height: 56, price: 4100, label: 'Original Size' }],
  },

  {
    title: "Still Life With Large Roemer, Lemon And Grapes",
    year: "1642",
    originalSize: "62 x 82 cm",
    artist: "Pieter Claesz",
    artistLife: "1597-1660",
    sku: "AM-PCL-004",
    basePrice: 7000,
    currency: "AED",
    image: "/image/c/still life with large roemer, lemon and grapes.jpg",
    options: [{ id: 'opt1', width: 62, height: 82, price: 7000, label: 'Original Size' }],
  },

  {
    title: "Tabletop Still Life Pigeon Pie And Delfware Jug",
    year: "1627",
    originalSize: "46 x 62 cm",
    artist: "Pieter Claesz",
    artistLife: "1597-1660",
    sku: "AM-PCL-005",
    basePrice: 5100,
    currency: "AED",
    image: "/image/c/tabletop still life pigeon pie and delfware jug.jpg",
    options: [{ id: 'opt1', width: 46, height: 62, price: 5100, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Catherine De Medici",
    year: "1555",
    originalSize: "32 x 23.5 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-001",
    basePrice: 2800,
    currency: "AED",
    image: "/image/c/portrait of catherine de medici.jpg",
    options: [{ id: 'opt1', width: 32, height: 23.5, price: 2800, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Francis I Roi De France",
    year: "1530",
    originalSize: "96 x 74 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-002",
    basePrice: 8500,
    currency: "AED",
    image: "/image/c/portrait of francis I roi de france.jpg",
    options: [{ id: 'opt1', width: 96, height: 74, price: 8500, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Elizabeth Of Austria",
    year: "1571",
    originalSize: "36 x 26 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-003",
    basePrice: 3000,
    currency: "AED",
    image: "/image/c/portrait of elizabeth of austria.jpg",
    options: [{ id: 'opt1', width: 36, height: 26, price: 3000, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Charles IX",
    year: "1570",
    originalSize: "32.5 x 23 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-004",
    basePrice: 2800,
    currency: "AED",
    image: "/image/c/portrait of charles IX.jpg",
    options: [{ id: 'opt1', width: 32.5, height: 23, price: 2800, label: 'Original Size' }],
  },

  {
    title: "Portrait Of King Charles IX Of France",
    year: "1566",
    originalSize: "53.5 x 41 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-005",
    basePrice: 4200,
    currency: "AED",
    image: "/image/c/portrait of king charles IX of france.jpg",
    options: [{ id: 'opt1', width: 53.5, height: 41, price: 4200, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Henri II King Of France",
    year: "1559",
    originalSize: "33.5 x 22.2 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-006",
    basePrice: 2700,
    currency: "AED",
    image: "/image/c/portrait of henri II king of france.jpg",
    options: [{ id: 'opt1', width: 33.5, height: 22.2, price: 2700, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Elizabeth Of Austris Queen Of France",
    year: "1571",
    originalSize: "32 x 22 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-007",
    basePrice: 2600,
    currency: "AED",
    image: "/image/c/portrait of elizabeth of austris queen of france.jpg",
    options: [{ id: 'opt1', width: 32, height: 22, price: 2600, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Louise De Lorraine",
    year: "1575",
    originalSize: "32 x 24 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-008",
    basePrice: 2700,
    currency: "AED",
    image: "/image/c/portrait of louise de lorraine.jpg",
    options: [{ id: 'opt1', width: 32, height: 24, price: 2700, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Mary Queen Of Scots",
    year: "1558",
    originalSize: "35 x 27.5 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-009",
    basePrice: 3000,
    currency: "AED",
    image: "/image/c/portrait of mary queen of scots.jpg",
    options: [{ id: 'opt1', width: 35, height: 27.5, price: 3000, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Odet De Coligny Cardinal Of Chatillon",
    year: "1560",
    originalSize: "29.2 x 23 cm",
    artist: "Francois Clouet",
    artistLife: "1510-1572",
    sku: "AM-FC-010",
    basePrice: 2600,
    currency: "AED",
    image: "/image/c/portrait of odet de coligny cardinal of chatillon.jpg",
    options: [{ id: 'opt1', width: 29.2, height: 23, price: 2600, label: 'Original Size' }],
  },

  {
    title: "Fish And Still Life",
    year: "1615",
    originalSize: "44 x 60 cm",
    artist: "Osias Beert the Elder",
    artistLife: "1580-1624",
    sku: "AM-OBE-001",
    basePrice: 4800,
    currency: "AED",
    image: "/image/c/fish and still life.jpg",
    options: [{ id: 'opt1', width: 44, height: 60, price: 4800, label: 'Original Size' }],
  },

  {
    title: "Gooseberries On A Table",
    year: "1608",
    originalSize: "35.2 x 48.8 cm",
    artist: "Osias Beert the Elder",
    artistLife: "1580-1624",
    sku: "AM-OBE-002",
    basePrice: 4000,
    currency: "AED",
    image: "/image/c/gooseberries on a table.jpg",
    options: [{ id: 'opt1', width: 35.2, height: 48.8, price: 4000, label: 'Original Size' }],
  },

  {
    title: "Four Apircots On A Stone Plinth",
    year: "1608",
    originalSize: "32.6 x 46.5 cm",
    artist: "Osias Beert the Elder",
    artistLife: "1580-1624",
    sku: "AM-OBE-003",
    basePrice: 3800,
    currency: "AED",
    image: "/image/c/four apircots on a stone plinth.jpg",
    options: [{ id: 'opt1', width: 32.6, height: 46.5, price: 3800, label: 'Original Size' }],
  },

  {
    title: "Three Peaches On A Stone Plinth",
    year: "1610",
    originalSize: "33.3 x 44 cm",
    artist: "Osias Beert the Elder",
    artistLife: "1580-1624",
    sku: "AM-OBE-004",
    basePrice: 3700,
    currency: "AED",
    image: "/image/c/three peaches on a stone plinth.jpg",
    options: [{ id: 'opt1', width: 33.3, height: 44, price: 3700, label: 'Original Size' }],
  },

  {
    title: "Still Life Lobster",
    year: "1615",
    originalSize: "43 x 58 cm",
    artist: "Osias Beert the Elder",
    artistLife: "1580-1624",
    sku: "AM-OBE-005",
    basePrice: 4700,
    currency: "AED",
    image: "/image/c/still life lobster.jpg",
    options: [{ id: 'opt1', width: 43, height: 58, price: 4700, label: 'Original Size' }],
  },

  {
    title: "Fruit Still Life With Basket Of Cheese",
    year: "1610",
    originalSize: "41 x 56 cm",
    artist: "Osias Beert the Elder",
    artistLife: "1580-1624",
    sku: "AM-OBE-006",
    basePrice: 4500,
    currency: "AED",
    image: "/image/c/fruit still life with basket of cheese.jpg",
    options: [{ id: 'opt1', width: 41, height: 56, price: 4500, label: 'Original Size' }],
  },

  {
    title: "Still Life Leg Of Mutton Bread",
    year: "1618",
    originalSize: "41.9 x 57 cm",
    artist: "Osias Beert the Elder",
    artistLife: "1580-1624",
    sku: "AM-OBE-007",
    basePrice: 4600,
    currency: "AED",
    image: "/image/c/still life leg of mutton bread.jpg",
    options: [{ id: 'opt1', width: 41.9, height: 57, price: 4600, label: 'Original Size' }],
  },

  {
    title: "Still Life Books Burning Candle",
    year: "1615",
    originalSize: "38 x 50.2 cm",
    artist: "Osias Beert the Elder",
    artistLife: "1580-1624",
    sku: "AM-OBE-008",
    basePrice: 4200,
    currency: "AED",
    image: "/image/c/still life books burning candle.jpg",
    options: [{ id: 'opt1', width: 38, height: 50.2, price: 4200, label: 'Original Size' }],
  },

  {
    title: "Rome A Caprice View With Ruins Based On The Forum",
    year: "1735",
    originalSize: "99 x 137 cm",
    artist: "Giovanni Paolo Panini",
    artistLife: "1691-1765",
    sku: "AM-GPP-001",
    basePrice: 12000,
    currency: "AED",
    image: "/image/c/rome a caprice view with ruins based on the forum.jpg",
    options: [{ id: 'opt1', width: 99, height: 137, price: 12000, label: 'Original Size' }],
  },

  {
    title: "The Coloseum",
    year: "1747",
    originalSize: "99 x 135 cm",
    artist: "Giovanni Paolo Panini",
    artistLife: "1691-1765",
    sku: "AM-GPP-002",
    basePrice: 11800,
    currency: "AED",
    image: "/image/c/the coloseum.jpg",
    options: [{ id: 'opt1', width: 99, height: 135, price: 11800, label: 'Original Size' }],
  },

  {
    title: "Marie-Anne Caralus Duran (The Artists Daughter)",
    year: "1873",
    originalSize: "46 x 38 cm",
    artist: "Carolus-Duran",
    artistLife: "1837-1917",
    sku: "AM-CD-001",
    basePrice: 4100,
    currency: "AED",
    image: "/image/c/marie-anne caralus duran (the artists daughter).jpg",
    options: [{ id: 'opt1', width: 46, height: 38, price: 4100, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Sarah Bernhardt",
    year: "1876",
    originalSize: "250 x 200 cm",
    artist: "Georges Clairin",
    artistLife: "1843-1919",
    sku: "AM-GCL-001",
    basePrice: 38000,
    currency: "AED",
    image: "/image/c/portrait of sarah bernhardt.jpg",
    options: [{ id: 'opt1', width: 250, height: 200, price: 38000, label: 'Original Size' }],
  },

  {
    title: "The Annunciation",
    originalSize: "122 x 180 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-001",
    basePrice: 17000,
    currency: "AED",
    image: "/image/c/the annunciation.jpg",
    options: [{ id: 'opt1', width: 122, height: 180, price: 17000, label: 'Original Size' }],
  },

  {
    title: "Head Of A Man",
    originalSize: "47 x 38 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-002",
    basePrice: 4100,
    currency: "AED",
    image: "/image/c/head of a man.jpg",
    options: [{ id: 'opt1', width: 47, height: 38, price: 4100, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Man Possibly Of Robert Arnauld Of Andilly",
    originalSize: "78 x 63 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-003",
    basePrice: 7000,
    currency: "AED",
    image: "/image/c/portrait of a man possibly of robert arnauld of andilly.jpg",
    options: [{ id: 'opt1', width: 78, height: 63, price: 7000, label: 'Original Size' }],
  },

  {
    title: "The Moorish Chief",
    originalSize: "50 x 40 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-004",
    basePrice: 4300,
    currency: "AED",
    image: "/image/c/the moorish chief.jpg",
    options: [{ id: 'opt1', width: 50, height: 40, price: 4300, label: 'Original Size' }],
  },

  {
    title: "A Corner Of My Studio",
    originalSize: "67.3 x 82 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-005",
    basePrice: 7400,
    currency: "AED",
    image: "/image/c/a corner of my studio.jpg",
    options: [{ id: 'opt1', width: 67.3, height: 82, price: 7400, label: 'Original Size' }],
  },

  {
    title: "The Antiquary Shop",
    originalSize: "67.3 x 82 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-006",
    basePrice: 7400,
    currency: "AED",
    image: "/image/c/the antiquary shop.jpg",
    options: [{ id: 'opt1', width: 67.3, height: 82, price: 7400, label: 'Original Size' }],
  },

  {
    title: "Dora Wheler",
    originalSize: "182.9 x 92.7 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-007",
    basePrice: 15000,
    currency: "AED",
    image: "/image/c/dora wheler.jpg",
    options: [{ id: 'opt1', width: 182.9, height: 92.7, price: 15000, label: 'Original Size' }],
  },

  {
    title: "I Think I Am Ready Now",
    originalSize: "95 x 74 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-008",
    basePrice: 8500,
    currency: "AED",
    image: "/image/c/i think i am ready now.jpg",
    options: [{ id: 'opt1', width: 95, height: 74, price: 8500, label: 'Original Size' }],
  },

  {
    title: "Quai Du Louvre In Winter",
    originalSize: "36.8 x 46 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-009",
    basePrice: 4000,
    currency: "AED",
    image: "/image/c/quai du louvre in winter.jpg",
    options: [{ id: 'opt1', width: 36.8, height: 46, price: 4000, label: 'Original Size' }],
  },

  {
    title: "St Paul's Cathedral",
    originalSize: "87.6 x 69.9 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-010",
    basePrice: 8000,
    currency: "AED",
    image: "/image/c/st paul's cathedral.jpg",
    options: [{ id: 'opt1', width: 87.6, height: 69.9, price: 8000, label: 'Original Size' }],
  },

  {
    title: "Austrian",
    originalSize: "62.2 x 51.4 cm",
    artist: "Unknown",
    sku: "AM-C-UNK-011",
    basePrice: 5200,
    currency: "AED",
    image: "/image/c/austrian.jpg",
    options: [{ id: 'opt1', width: 62.2, height: 51.4, price: 5200, label: 'Original Size' }],
  },

];

export default cArtworks;
